[build]
  command = "npm run build"
  publish = "web"

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200

[[redirects]]
  from = "/api/blob-put"
  to = "/.netlify/functions/api/blob-put"
  status = 200

[[redirects]]
  from = "/api/blob-get"
  to = "/.netlify/functions/api/blob-get"
  status = 200

[[redirects]]
  from = "/api/db-migrate"
  to = "/.netlify/functions/api/db-migrate"
  status = 200

[[redirects]]
  from = "/api/upload"
  to = "/.netlify/functions/api/upload"
  status = 200

[[redirects]]
  from = "/api/ingest-start"
  to = "/.netlify/functions/api/ingest-start"
  status = 200

[[redirects]]
  from = "/api/doc-status"
  to = "/.netlify/functions/api/doc-status"
  status = 200

[[redirects]]
  from = "/api/rag-query"
  to = "/.netlify/functions/api/rag-query"
  status = 200

[functions]
  "scheduled/nightly-maintenance" = { schedule = "0 2 * * *" }
